.TH io.elementary.calendar-daemon 1 "May 28, 2014"
.SH NAME
io.elementary.calendar-daemon \- calendar event notification service
.PP
\fBio.elementary.calendar-daemon\fP provides desktop notifications for upcoming events
from Evolution Data Server. It is typically autostarted on login.
.SH AUTHOR
io.elementary.calendar-daemon was written by Corentin Noël <corentin@elementaryos.org>
.PP
This manual page was written by Sergey "Shnatsel" Davidoff <sergey@elementaryos.org>,
for the Debian project (but may be used by others).
